stages:
  - build
  - test
  - checkstyle
  - deploy

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - mvn clean package

test:
    stage: test
    image: maven:3.3.9-jdk-8
    script:
    - echo "Test DEMO app"
    - mvn test && mvn jacoco:report
    - cat target/site/jacoco/index.html | grep -o '.*'
    coverage: "/Total.*?([0-9]{1,3})%/"


checkstyle:
    stage: checkstyle
    image: maven:3.3.9-jdk-8
    script:
    - echo "Checkstyle DEMO app"
    - mvn checkstyle:check

variables:
    DB_IP: ec2-18-202-1-222.eu-west-1.compute.amazonaws.com
    DB_PORT: 5432
    DB_USER: ybpntmtzwyesgi
    DB_PASSWORD: c50f5de90b4314b0d3e3f85067c2b2b32dfb1d2db128b153838ad9f474c2bc93
    DB_DBNAME: d10kou89vetn37
    
deploy:
  stage: deploy
  image: ruby:2.4
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=project1-anapistanila --api-key=$HEROKU_API_KEY
  only:
    - production
